# Generated by Django 4.2.6 on 2024-01-17 08:26

import blogapp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(default=blogapp.models.uuid_generate, max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('pub_date', models.DateField(null=True)),
                ('page', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('is_delete', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
